---
title: "2018-12-12"
output: html_notebook
---
```{r}
knitr::opts_chunk$set(echo = TRUE)
library(readr); library(dplyr); library(stringr); library(lubridate)
```

```{r}
library(readr)
libraryData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/library100_102.csv")
```

```{r}
libraryData$"‘ĞŠÙåU’n" <- as.factor(libraryData$"‘ĞŠÙåU’n")
storageLocations <-levels(libraryData$"‘ĞŠÙåU’n")
```

```{r}
libraryData$"‘ĞŠÙåU’n" %>% as.factor() %>% levels() -> storageLocations
```

```{r}
i <- 1
# 1
storageLocation_i <- storageLocations[i] 
# 2
numericalIndexForSubsample<-which(libraryData$"‘ĞŠÙåU’n" == storageLocation_i)
subsample_i <- libraryData[numericalIndexForSubsample,]
# 3
borrowCount_i <- nrow(subsample_i)
```

```{r}
# 0
allBorrowCount <- vector("numeric",18)
```

```{r}
i<-3
  # 1
  storageLocation_i <- storageLocations[i] 
  # 2
  numericalIndexForSubsample<-which(libraryData$"‘ĞŠÙåU’n" == storageLocation_i)
  subsample_i <- libraryData[numericalIndexForSubsample,]
  # 3
  borrowCount_i <- nrow(subsample_i)
  # 4
  allBorrowCount[[i]]<-borrowCount_i
```

```{r}
# 0
allBorrowCount <- vector("numeric",18)
for(i in c(1:18)){
  # 1
  storageLocation_i <- storageLocations[i] 
  # 2
  numericalIndexForSubsample<-which(libraryData$"‘ĞŠÙåU’n"==storageLocation_i)
  subsample_i <- libraryData[numericalIndexForSubsample,]
  # 3
  borrowCount_i <- nrow(subsample_i)
  # 4
  allBorrowCount[[i]]<-borrowCount_i  
}
```

##???ŒÂ›{‰@Ø‘—Ê
```{r}
#æŠÅ—LŠôŒÂ›{‰@
CollegeBorrow <- libraryData$"›{‰@" %>% as.factor() %>% levels() 
#İ’èvector—LŠôŒÂ(i)
allCollegeBorrowCount <- vector("numeric",6)
#6‰Â—plength(collegeBorrow)
#ŒvZ
for (i in c(1:6)) {
  #QoˆêŒÂ—vŒvZ“I›{‰@
  CollegeBorrow_i <- CollegeBorrow[i]
  #œnŒ´‘—¿’†Qo—LŠôŒÂ›¢‰—ŠY›{‰@
  CollegeBorrowSubsample <- which(libraryData$"›{‰@" == CollegeBorrow_i)
  #›’ã–Ê“I‘—¿æo
  CollegeBorrowSubsample_i <- libraryData[CollegeBorrowSubsample,]
  #ZoŠY›{‰@Ø‘—Ê
  CollegeBorrowCount_i <- nrow(CollegeBorrowSubsample_i)
  #–×‘¶Š???ŒÂ›{‰@‘—¿
  allCollegeBorrowCount[[i]] <- CollegeBorrowCount_i
}
```

##???ŒÂ›{¶“IØ???ŸÉ
```{r}
StudentBorrow <- libraryData$"›{åj" %>% as.factor() %>% levels()
#StudentBorrow <- libraryData$"›{åj" %>% unique()
allStudentBorrowCount <- vector("numeric",length(StudentBorrow))
for (i in c(1:length(StudentBorrow))) {
  StudentBorrow_i <- StudentBorrow[i]
  StudentBorrowSubsample <- which(libraryData$"›{åj" == StudentBorrow_i)
  StudentBorrowSubsample_i <- libraryData[StudentBorrowSubsample,]
  StudentBorrowCount_i <- nrow(StudentBorrowSubsample_i)
  allStudentBorrowCount[[i]] <- StudentBorrowCount_i
 }
```

```{r}
libraryData %>%
  group_by(‘ĞŠÙåU’n) %>%
  #•ªD18ŒÂ
  summarise(
    borrowCount=length(›{åj)
  ) %>%
  ungroup -> result
result
```
```{r}
# 0
allBorrowCount <- vector("numeric",18)
for(i in c(1:18)){
  # 1
  storageLocation_i <- storageLocations[i] 
  # 2
  numericalIndexForSubsample<-which(libraryData$‘ĞŠÙåU’n==storageLocation_i)
  subsample_i <- libraryData[numericalIndexForSubsample,]
  # 3
  borrowCount_i <- length(subsample_i$›{åj)
  # 4
  allBorrowCount[[i]]<-borrowCount_i  
}
```
```{r}
libraryData %>%
  mutate(
    ›{Œn = str_sub(›{åj,5,6)
    ##‘Šác‰— libraryData$›{Œn <- str_sub(libraryData$›{åj,5,6)
  )
```

```{r}
libraryData %>%
  group_by(›{‰@,“ü›{”N) %>%
  summarise(
    borrowCount=length(›{åj)
  ) %>%
  ungroup -> result2
result2
```

```{r}
#0 container
a <- length(libraryData$"›{‰@" %>% unique())
b <- length(libraryData$"“ü›{”N" %>% unique())
CollegeEntranceYearBorrow <- a*b
for (i in seq_along(College)) {
  for (j in seq_along(EntranceYear)) {
    #1
    
    #2
    
    #3
    
    #4
    
  }
}
```

#Qo???ŒÂ›{¶“I‘æˆê•MØ???ŠÔ
```{r}
libraryData$"Ø???ŠÔ" <- ymd_hms(libraryData$"Ø???ŠÔ",tz = "Asia/Taipei")
libraryData %>%
  group_by(›{åj) %>%
  summarise(
    ‘æˆê•MØ???ŠÔ=min(Ø???ŠÔ)
  ) %>%
  ungroup -> result3
result3
```


```{r}
libraryData %>%
  mutate(
    Ø???ŠÔ = ymd_hms(Ø???ŠÔ,tz="Asia/Taipei")
  ) %>%
  group_by(›{åj) %>%
  summarise(
    ‘æˆê•MØ???ŠÔ=min(Ø???ŠÔ)
  ) %>%
  ungroup -> result3
result3
```





###

$$\sum_{i=1}^{10} i$$

```{r}
ans<-0
for(i in 1:10){
  newlyAdded<-i
  ans<-ans+newlyAdded
}
```



